### ISSUE TITLE
Increase the timeout beyond 1 minute

### ISSUE THREAD

**Issue by IvanKonov** [dokan-dev/dokan-dotnet#147]
Tell me how to increase the timeout more than 1 minute?
```
        public Char Mount(Int32 thread_count)
        {
            this.label_disk = IOClass.GetFreeLabelDisk();
            const DokanOptions dokan_options = DokanOptions.DebugMode | DokanOptions.NetworkDrive;
            Task.Run(
                action: () => this.Mount(
                    mountPoint: $"{this.label_disk}:\\",
                    mountOptions: dokan_options,
                    threadCount: thread_count,
                    version:110,
                    timeout:TimeSpan.FromMinutes(value: 10),
                    logger: DokanLogger)).ForgetSafely();

            return this.label_disk;
        }
```
On my very slow data source, reading a file of 100 MB is interrupted after 1 minute

**Comment by IvanKonov** [comment]
![image](https://user-images.githubusercontent.com/20556427/27646085-6b903f22-5c30-11e7-8515-2541736398b8.png)

**Comment by marinkobabic** [comment]
During the read you are getting multiple requests. You can reset the
timeout inside of the read method for large files. There should be a method
resetTimeout.

Am 28.06.2017 17:27 schrieb "IvanKonov" <notifications@github.com>:

Tell me how to increase the timeout more than 1 minute?

        public Char Mount(Int32 thread_count)
        {
            this.label_disk = IOClass.GetFreeLabelDisk();
            const DokanOptions dokan_options = DokanOptions.DebugMode
| DokanOptions.NetworkDrive;
            Task.Run(
                action: () => this.Mount(
                    mountPoint: $"{this.label_disk}:\\",
                    mountOptions: dokan_options,
                    threadCount: thread_count,
                    version:110,
                    timeout:TimeSpan.FromMinutes(value: 10),
                    logger: DokanLogger)).ForgetSafely();

            return this.label_disk;
        }

On my very slow data source, reading a file of 100 MB is interrupted after
1 minute

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dokan-dev/dokan-dotnet/issues/147>, or mute the thread

**Comment by IvanKonov** [comment]
> During the read you are getting multiple requests. You can reset the
timeout inside of the read method for large files. There should be a method
resetTimeout.

Thank you! It really helped me!
Tell me, please, why do I specify a timeout when mounting?

**Comment by marinkobabic** [comment]
Sometimes it takes long to get the drive mounted. This is the default
value. The system limits us having a much higher value and not the Dolan.

Am 28.06.2017 18:04 schrieb "IvanKonov" <notifications@github.com>:
