### ISSUE TITLE
create instance of DokanFileInfo for testing

### ISSUE THREAD

**Issue by ghosttie** [dokan-dev/dokan-dotnet#183]
In order to avoid blue screens while my file system is in an early stage, I'm implementing the IDokanOperations functions one at a time and testing them just in .NET, but to test some of the functionality I need to be able to create an instance of DokanFileInfo, which isn't currently possible.

Is there any chance you could add a way to create instances of DokanFileInfo for testing?

**Comment by Liryna** [comment]
Hi @ghosttie ,

Your request is to expose DokanFileInfo outside the dll ?
The simplest would be to copy the class temporarily in your code.

Otherwise than this, I don't think this class has a purpose other than in IDokanOperations .

**Comment by ghosttie** [comment]
I'd like to test IDokanOperations using .NET code without using the driver, but I can't do that because there isn't a constructor on DokanFileInfo.

If you wanted to support this type of testing you could use the impostor pattern: add an IDokanFileInfo interface which DokanFileInfo implements.  IDokanOperations would be changed to expect an IDokanFileInfo instead of a DokanFileInfo, and then a test class that implements IDokanOperations could be used for testing instead of a real DokanFileInfo.

**Comment by Liryna** [comment]
OK I see 👍  I will let this open to see if others would like to see it happen.

**Comment by kyanha** [comment]
I created a testing framework of this kind by basically creating wrappers around 

There's a way to do it using System.Runtime.Serialization and System.Reflection.  About the only thing you can't do with this is call OpenRequestor():

```cs
using DokanNet;
using System.Diagnostics;
using System.Reflection;
using static System.Reflection.BindingFlags;
using System.Runtime.Serialization;

var dfitype = typeof(DokanFileInfo);
var dfiMockObject = (DokanFileInfo)FormatterServices.
                    GetUninitializedObject(typeof(DokanFileInfo));
var piofield = dfitype.GetField("_pagingIo",
                    GetField|NonPublic|Instance);
piofield.SetValue(dfiMockObject,true); // Set PagingIo true
var syncIofield = dfitype.GetField("_synchronousIo",
                    GetField|NonPublic|Instance);
syncIoField.SetValue(dfiMockObject,true); // Set SynchronousIo true
var noCacheField = dfitype.GetField("_noCache",
                    GetField|NonPublic|Instance);
noCacheField.SetValue(dfiMockObject,true); // Set NoCache true
var w2eofField = dfitype.GetField("_writeToEndOfFile",
                    GetField|NonPublic|Instance);
w2eofField.SetValue(dfiMockObject,true); // Set WriteToEndOfFile true
var pidField = dfitype.GetField("_processId",
                    GetField|NonPublic|Instance);
pidField.SetValue(dfiMockObject,Process.GetCurrentProcess().Id);
dfiMockObject.Directory = true;
dfiMockObject.DeleteAtClose = true;
```

**Comment by kyanha** [comment]
Alternatively, you can do what @ghosttie suggested, and make it an Impersonation pattern.

That's pretty much what I do in my wrapper -- in the IDokanOperations methods that receive a DokanFileInfo, I construct a new object with an interface that matches DokanFileInfo and pass that through to the implementations that actually do exactly the same thing that direct Dokan implementations do, and for testing I construct a new mockable object with the same interface.

Still, it would be very nice not to have to fight with the tedium of creating a framework just to follow good design practices.

**Comment by Liryna** [comment]
@magol do you have an opinion on this ?
Seems like @ghosttie is not alone to have DokanFileInfo available

@kyanha I also agree that probably @ghosttie way is a cleaner way to do this.
It would avoid the `Testing` member. In the meantime, we can also directly include in dokan a testing class that inherit from IDokanOperations if you have something in mind.

**Comment by kyanha** [comment]
The main thing that we (that is, people who do Test-Driven Development) have a problem with is that we need some way to create the DokanFileInfo.  (n.b.: I have no association with ghosttie, don't know them from anywhere, and my reason for asking for this capability is completely separate from theirs.)

Our test harnesses can deal with our IDokanOperations implementations, call their members with varying parameters, and verify their return values and back-end structures.  But our test coverage relies on us being able to branch based on values in the passed DokanFileInfo.  Unless we can do that, our tests are always going to be suboptimal.

I do have some ideas in mind for something, and I'll put them in a pull request when I've got a free several hours.

**Comment by magol** [comment]
I understand the frustration  for users that try to implement unit tests for this. I like the approach with `IDokanFileInfo`, that is the most flexible solution. I imagine that it should not ruin backward compatibility for most users.

**Comment by marinkobabic** [comment]
(DokanFileInfo)Activator.CreateInstance(typeof(DokanFileInfo)) and the job is done. Is this not an option?

**Comment by marinkobabic** [comment]
@kyanha
This means a public constructor would not solve your problem?

**Comment by kyanha** [comment]
@Liryna We can't really do any changes on the signatures for the methods required by IDokanOperations, because if we did we'd not be actually exercising the code under test.  (i.e., we'd still need some translation layer from Dokan.Net to our code.)  A testing class that inherits from IDokanOperations won't really be a lot of help unless or until we can mock DokanFileInfo.

The test framework I made for myself is as close as I could get to the minimum translation layer necessary to get it to work.  Because the last parameter of all of these methods is sealed DokanFileInfo, I basically end up wrapping the DFI in an object of an interface I created, and just forward all the property and method calls to the wrapped DFI.  For mocking, I created another class (of the same interface) that let me specifically set the values and responses that I wanted.

I separated out my test framework and put it into a separate repo for you to look at and tell me what part of it (if any) you want me to bring over to Dokan itself.  It can be found at https://github.com/kyanha/TestableDokan.git.  Of it, the forwarding and new interface that matches DFI would need to be in Dokan, and the mocked implementation of that interface would properly go in the client testing project.

**Comment by kyanha** [comment]
@marinkobabic GetRequestor() and TryResetTimeout() would have been supported well enough for testing in #184, but Liryna wants to separate testability into its own class by making the final parameters of all the Dokan operations take an IDokanFileInfo instead of a sealed DokanFileInfo.  Doing that changes the binary compatibility for dokannet.dll; fortunately, that DLL is usually imported by NuGet (and deployed with the final application) instead of being installed globally.

**Comment by kyanha** [comment]
@Liryna Unfortunately, this is a source-breaking change.  See #239 -- all implementations of `IDokanOperations` would need to change all their final parameters to be `IDokanFileInfo` instead of `DokanFileInfo`.

I could rename `IDokanFileInfo` in there to be `DokanFileInfo` (renaming the current `DokanFileInfo` to something like `DokanKernelFileInfo`), and it wouldn't be a source-breaking change, but that would break the IPrefix naming convention for interfaces.

What do you think is the best approach?

**Comment by Liryna** [comment]
Hi @kyanha 

Thank you for your contribution.
`IDokanFileInfo` we can keep as you did. The API break is not important. Will be easy to replace as you did 👍

**Comment by kyanha** [comment]
When do you think it might be merged?  (What version would I be looking at to include it?)

**Comment by Liryna** [comment]
It can be merged fast. I just wanted to check why only this PR seems to fully fail without running the test: https://ci.appveyor.com/project/Liryna/dokan-dotnet/builds/27896502/job/yauv6cx4mvg9fhce

**Comment by kyanha** [comment]
> 
> 
> It can be merged fast. I just wanted to check why only this PR seems to fully fail without running the test: https://ci.appveyor.com/project/Liryna/dokan-dotnet/builds/27896502/job/yauv6cx4mvg9fhce

It looks like this includes the targetmoniker changes, which means that 'net4.0' and 'net4.6' need to be modified to 'net40' and 'net46'.

Also, the appveyor script has another bug, because the invokation of run-winfstest.bat needs to include a trailing backslash for N:\TMP\.  Otherwise, it ends up creating N:\TMPnnnnnn\ directories, which end up as C:\TMPnnnnnn\ directories.  I'll be pushing a new appveyor.yml in a moment.

**Comment by kyanha** [comment]
@Liryna appveyor operates now.  https://ci.appveyor.com/project/Liryna/dokan-dotnet/builds/27904450/job/5jkr4h87scqjrdo4 is the latest.  10 winfstest failures, 30 DokanNet.Tests failures.

**Comment by kyanha** [comment]
I put the framework moniker changes in PR #243, so I'll redo #239 without it.

**Comment by Liryna** [comment]
Thanks to @kyanha contribution, this issue is now solved 🚀
