### ISSUE TITLE
Add return value for CloseFile and Cleanup

### ISSUE THREAD

**Issue by pp111** [dokan-dev/dokan-dotnet#233]
Currently CloseFile and Cleanup does not have return values (NtStatus). So we can not inform the driver that the operation did not succeed.

For example, my applications works with a remote slow storage, I handle the write operations with a local cache but when the file is closed I upload it to the remote server. If the upload fails I couldn't find a way to tell the driver that the operation failed and the file is not copied.

**Comment by Liryna** [comment]
Hi @pp111 

We could allow to return a status during Close/Cleanup but some "usual" driver behavior is to block the close until it can return `SUCCESS`. More over, return a failure at this point would have most of the time no effect since not much application is looking at the return value of `CloseHandle`.
In your case, I would propose you delay the close of the time you need OR return directly and schedule in the background to save your data to the storage.

**Comment by pp111** [comment]
Thank you for the ideas. There could be situations where retrying will never succeed or other situations where it can take a lot of time (internet is down, the server has a problem,...)

The problem is mainly with the Windows Explorer doing a "Move file" operation. If we can not tell the driver that the operation failed, Windows Explorer will delete the source file. If we could return an error and hopefully Windows Explorer checks CloseHandle return value this situation could be handled.

**Comment by Liryna** [comment]
I understand your need but this situation need to be handled by your application.

**Comment by pp111** [comment]
Yes, I think Explorer does not check if CloseHandle is successful. I forced a timeout but still Explorer thinks the operation is ok.

Anyway, when a delete file operation fails, again we have no way to return to the driver an error code (from Cleanup). 

Please think if it is worth to add a return value for CloseFile/Cleanup functions. Some programs may check it.

**Comment by Liryna** [comment]
Delete operations should be checked during the CreateFile or during the DeleteFile. When Cleanup will be called, you need to be ready to do the delete against any failure.
