### ISSUE TITLE
MoveFile with Folders

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#25]
Hello,
In my code, when someone tries to move one folder to another that already exists, with the replace boolean set to false,
he receives NtStatus.ObjectNameCollision, just like in the scenario with files.

When I run my code, and try to do this operation, it just fails, and there is no prompt window that asks me if I want to replace the existing directory.
The operation does work with files, just not with folders.
Maybe I should return a different error code?
Help will be appreciated.

**Comment by Liryna** [comment]
Hi @shlatchz ,

Yes, NtStatus.ObjectNameCollision is the good value to return.

Because of your report, I tested with the mirror and found that MoveFile was not supporting directories :laughing: 
So I made it for making your test https://github.com/dokan-dev/dokan-dotnet/commit/0026d1d3b6487554d6209432598ff435309370b3

Unfortunatly, I have also not been able to get a windows prompt.
BUT I made a test with normal NTFS volume and I get also no prompt.

Do you have a exemple where in NTFS volume you get a prompt and not in dokan ?

**Comment by shlatchz** [comment]
I just tried moving Directory named "A" to directory "B" that contains a directory named "A" in it,
and I did get a prompt.

![jjjjj](https://cloud.githubusercontent.com/assets/4594463/10294282/e23ddd3e-6bc1-11e5-98b8-b76defb45fc0.png)

**Comment by Liryna** [comment]
I cannot make the test :cry: It seems that in windows 10, he directly merge the two folders.

Otherwise you can use Process Monitor https://technet.microsoft.com/en-us/library/bb896645.aspx
To see what is the answer of the NTFS Volume at the merge time and compare with your code.

**Comment by shlatchz** [comment]
Weirdly the bug only happens when I drag (Move) folder "A" to folder "B" (when "A" exists inside "B")
but it doesn't happen when I copy folder "A" to folder "B".
When I copy, I see the message that folder "A" exists in "B".
Procmon shown "Name Collision" in both instances...

**Comment by Liryna** [comment]
I made my test when I drag, could not get the merge message.
Anyway, I don't think it is a dokan issue. Explorer react on the information that you provide.
Maybe there is still a difference, but I cannot tell you which.

**Comment by shlatchz** [comment]
You are right. There was an issue when a folder was passed in CreateFile.
Thanks!
